#!/bin/bash
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

db=${HOME}/.reflektor_do
default_action="true"

test -f $fb || touch $db

direction=$1
tagid=$2

if grep -qE "$1 $2" $db; then
	eval `grep -E "^$direction $tagid" $db | cut -d: -f2`
else
	echo "Entering '$direction $tagid' as null action"
	printf "%s %s:%s\n" $direction $tagid "$default_action" >> $db
fi
